# Generated by Django 2.2.5 on 2020-03-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=20)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Content',
            },
        ),
    ]
